//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eOckovanie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int docId { get; set; }
        public string userId { get; set; }
        public System.TimeSpan time1 { get; set; }
        public System.TimeSpan time2 { get; set; }
        public string status { get; set; }
        public string location { get; set; }
        public int vacId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Vaccines Vaccines { get; set; }
    }
}
